### ISSUE TITLE
Crashing Settings activity does not return / clean up correctly

### ISSUE THREAD

**Issue by coxtor** [renyuneyun/EaserOperationPluginExample#1]
I, I wanted to try out the external plugin possibilities options, sadly the return activity does not function correctly. After exiting the EditData Activity the application crashes, here the logcat:

`2018-11-20 15:25:30.182 22960-22960/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ryey.easeroperationpluginexample, PID: 22960
    java.lang.IllegalStateException: Could not find method finishActivity(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'btn_accept'
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:423)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:380)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by renyuneyun** [comment]
This seems strange as I can't reproduce the problem.
Could you give a more detailed explanation? Do you encounter this every time you do so?
